<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition="'$(Configuration)' == ''">Release</Configuration>
    <Platform Condition="'$(Platform)' == ''">AnyCPU</Platform>
    <OutputType>WinExe</OutputType>
    <AssemblyName>MemoryDesktop</AssemblyName>
    <RootNamespace>MemoryDesktop</RootNamespace>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>memory.ico</ApplicationIcon>
    <StartupObject>MemoryDesktop.Program</StartupObject>
    <PlatformTarget>x64</PlatformTarget>
    <Optimize>true</Optimize>
    <DebugType>pdbonly</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" /><Reference Include="System.Core" />
    <Reference Include="System.Xml" /><Reference Include="System.Xaml" /><Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" /><Reference Include="WindowsBase" />
    <Reference Include="PresentationCore" /><Reference Include="PresentationFramework" />
  </ItemGroup>
  <ItemGroup><Compile Include="*.cs" /></ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
